# Generated by Django 3.1 on 2020-08-26 12:08

import auctions.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to=auctions.util.user_directory_path),
        ),
    ]
