# Generated by Django 3.1 on 2020-08-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_wathlistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WathlistItem',
            new_name='WatchlistItem',
        ),
    ]
