# Generated by Django 3.1 on 2020-09-02 15:35

import auctions.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200902_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to=auctions.util.user_directory_path),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='auctions.listing'),
        ),
    ]
