# Generated by Django 3.1 on 2020-09-03 13:59

import auctions.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, upload_to=auctions.util.user_directory_path),
        ),
    ]
